"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Pessoa_1 = require("./Pessoa");
var ask = require('readline-sync');
console.clear();
var nome = ask.question("Nome: ");
console.clear();
var sobrenome = ask.question("Sobrenome: ");
console.clear();
var nomeDoPai = ask.question("Nome do pai: ");
console.clear();
var nomeDaMae = ask.question("Nome da mae: ");
console.clear();
var rg = ask.question("RG: ");
console.clear();
var cpf = ask.question("CPF: ");
console.clear();
var nasc = ask.question("Nascimento(DDMMAAAA): ");
var pessoa = new Pessoa_1.Pessoa(nome, sobrenome, nomeDoPai, nomeDaMae, rg, cpf, nasc);
pessoa.getPessoa();
